name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download-sources-from-crowdin:
    if: github.repository == 'grafana/grafana'
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-download.yml@d227dc3a2a2f241c3e0ca3dbab103069ff979f9a
    with:
      crowdin_project_id: 5
      pr_labels: 'area/frontend, area/internationalization, no-changelog, no-backport'
      github_board_id: 78 # Frontend Platform project
      en_paths: public/locales/en-US/grafana.json, public/app/plugins/datasource/azuremonitor/locales/en-US/grafana-azure-monitor-datasource.json, public/app/plugins/datasource/mssql/locales/en-US/mssql.json, packages/grafana-prometheus/src/locales/en-US/grafana-prometheus.json, packages/grafana-sql/src/locales/en-US/grafana-sql.json
