name: Crowdin automatic task management

on:
  workflow_dispatch:
  # once a month on the first day of the month at midnight
  schedule:
    - cron: "0 0 1 * *"

jobs:
  create-tasks-in-crowdin:
    if: github.repository == 'grafana/grafana'
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-create-tasks.yml@d227dc3a2a2f241c3e0ca3dbab103069ff979f9a
    with:
      crowdin_project_id: 5
