name: Verify i18n

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - release-*.*.*

jobs:
  verify-i18n:
    # Run on `grafana/grafana` main branch, or on pull requests to prevent double-running on mirrors
    if: (github.event_name == 'pull_request' || (github.event_name == 'push' && github.repository == 'grafana/grafana'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - run: yarn install --immutable --check-cache
      - run: yarn i18n-extract
      - name: Check for uncommitted translations
        run: |
          git show HEAD:public/locales/en-US/grafana.json | jq --sort-keys . > /tmp/grafana-i18n-before.json
          jq --sort-keys . public/locales/en-US/grafana.json > /tmp/grafana-i18n-after.json
          diff -u /tmp/grafana-i18n-before.json /tmp/grafana-i18n-after.json
          git diff --exit-code -- ':!public/locales/en-US/grafana.json'
