name: PR automation
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
permissions: {}
concurrency:
  group: pr-commands-${{ github.event.number }}
jobs:
  main:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands
        uses: grafana/grafana-github-actions/commands@3c62d35c5a66e730186a338e45aeb8fa784e2d56 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configPath: pr-commands
